default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode
  template: template0
  host: localhost
  username: taskman
  password: taskman

development:
  <<: *default
  database: taskman_dev

test:
  <<: *default
  database: taskman_test

